services:
  web:
    image: bun-app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
