const RockPodcastEpisode = {
  contentChannelId: 95,
  contentChannelTypeId: 22,
  title: "How to Be the Encourager Everyone Needs—Including You",
  content:
    '<p>How do you become the biggest encourager in the room? In this episode, Oneka McClellan is sharing practical ways to speak life.</p><h3><b>SHOW NOTES</b></h3><p><b>So Good Moments:&nbsp;</b></p><p class=""></p><ul><li><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">How Oneka’s (single) mom instilled courage in her at a young age and left a legacy of abundance instead of lack.</span></li><li><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">How we can leave people with a “new song in their heart” like the biblical story of Mary and Elizabeth.&nbsp;</span></li><li><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">Practical ways we can change the tide on social media from competing to cheering each other on.&nbsp;</span></li><li><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">How one message at church gave Oneka a different vision for her relationships.</span></li><li><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">How Oneka and her husband cultivate a spirit of honor in their home…and more!</span>&nbsp;</li></ul><p><b style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;"><br></b><b style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">Discussion Questions:&nbsp;</b></p><ol><li>What was your favorite part of this episode?</li><li>Who is one of the biggest encouragers you know and how have they impacted your life?&nbsp;</li><li>What is one small way you encourage yourself when you’re down?&nbsp;</li><li>How does the story of Mary and Elizabeth’s friendship inspire you?&nbsp;</li><li>What is one way you will encourage someone else this week?</li></ol><p><b>Resources:</b></p><p><a href="https://www.amazon.com/s?k=born+royal+oneka+mcclellan&amp;hvadid=698219331496&amp;hvdev=c&amp;hvexpln=67&amp;hvlocphy=9013098&amp;hvnetw=g&amp;hvocijid=4476165642106454721--&amp;hvqmt=e&amp;hvrand=4476165642106454721&amp;hvtargid=kwd-2306092395005&amp;hydadcr=22161_13517530&amp;mcid=841288b0c3fe33b8b1d9bc359196edaa&amp;tag=googhydr-20&amp;ref=pd_sl_8frc4decta_e_p67" target="_blank">Oneka’s Book: Born Royal</a><br><a href="https://www.bettertogether.tv/" target="_blank">Better Together TV</a><br><a href="https://www.shorelinecity.church/about" target="_blank">Shoreline City Church</a><br><a href="https://rock.gocf.org/page/2849" target="_blank" style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; background-color: rgb(255, 255, 255);">Shownotes Plus</a><br><a href="https://www.christfellowship.church/sisterhood" target="_blank" style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; background-color: rgb(255, 255, 255);">Learn more about Sisterhood</a><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;;">&nbsp;<br></span><a href="https://forms.gle/uTb868KYs2jfSh9f6" target="_blank" style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; background-color: rgb(255, 255, 255);">Ask a Question</a><br><a href="https://www.christfellowship.church/so-good-sisterhood" target="_blank" style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; background-color: rgb(255, 255, 255);">All Episodes</a></p><h5 class="">© 2022 Be Essential Songs (BMI) / Jord A Lil Music (BMI) / Doejones20 (BMI) (admin at <a href="https://EssentialMusicPublishing.com" target="_blank">EssentialMusicPublishing.com</a>). All rights reserved. Used by permission.</h5>',
  structuredContent: null,
  priority: 0,
  status: 2,
  approvedByPersonAliasId: 149917,
  approvedDateTime: "2025-07-18T11:29:59.697",
  startDateTime: "2025-07-21T00:00:00",
  expireDateTime: null,
  permalink: null,
  order: 0,
  itemGlobalKey: "how-to-be-the-encourager-everyone-needsincluding-you",
  isContentLibraryOwner: null,
  contentLibrarySourceIdentifier: null,
  contentLibraryLicenseTypeValueId: null,
  contentLibraryContentTopicId: null,
  contentLibraryUploadedByPersonAliasId: null,
  contentLibraryUploadedDateTime: null,
  experienceLevel: null,
  additionalSettingsJson: null,
  contentChannel: null,
  contentChannelType: null,
  createdDateTime: "2025-07-18T11:29:59.837",
  modifiedDateTime: "2025-07-18T11:29:59.837",
  createdByPersonAliasId: 149917,
  modifiedByPersonAliasId: 149917,
  modifiedAuditValuesAlreadyUpdated: false,
  attributes: {
    summary: {
      key: "Summary",
      name: "Subtitle",
      id: 39234,
    },
    titleOverride: {
      key: "TitleOverride",
      name: "Title Override",
      id: 41668,
    },
    image: {
      key: "Image",
      name: "Image File",
      id: 39235,
    },
    video: {
      key: "Video",
      name: "Video File",
      id: 41666,
    },
    videoLink: {
      key: "VideoLink",
      name: "Video Link",
      id: 50340,
    },
    audio: {
      key: "Audio",
      name: "Audio File",
      id: 41665,
    },
    metadata: {
      key: "Metadata",
      name: "Metadata",
      id: 53862,
    },
    shareMessage: {
      key: "ShareMessage",
      name: "Share Message",
      id: 55389,
    },
    hideFromSearch: {
      key: "HideFromSearch",
      name: "Hide From Search",
      id: 70701,
    },
    scriptures: {
      key: "Scriptures",
      name: "Beta | Scriptures",
      id: 71610,
    },
    theme: {
      key: "Theme",
      name: "Beta | Theme",
      id: 115363,
    },
    contentTags: {
      key: "ContentTags",
      name: "Content Tags",
      id: 147849,
    },
    additionalResources: {
      key: "AdditionalResources",
      name: "Additional Resources - Web 3.0",
      id: 209106,
    },
    pathname: {
      key: "pathname",
      name: "Url - Web 3.0",
      id: 209133,
    },
    securityDataViews: {
      key: "SecurityDataViews",
      name: "Limit to these DataView",
      id: 179741,
    },
    author: {
      key: "Author",
      name: "Author",
      id: 113384,
    },
    cardTitle: {
      key: "CardTitle",
      name: "Card Title",
      id: 113385,
    },
    url: {
      key: "Url",
      name: "Url",
      id: 113386,
    },
    callsToAction: {
      key: "CallsToAction",
      name: "Calls To Action",
      id: 113389,
    },
    rockLabel: {
      key: "RockLabel",
      name: "Rock Label",
      id: 153660,
    },
    podcastSeason: {
      key: "PodcastSeason",
      name: "Podcast Season",
      id: 201088,
    },
    media: {
      key: "Media",
      name: "Media",
      id: 207848,
    },
  },
  attributeValues: {
    summary: {
      attributeId: 39234,
      entityId: 19518,
      value: "Season 13 | Episode 4",
      valueFormatted: "Season 13 | Episode 4",
      persistedTextValue: "Season 13 | Episode 4",
      persistedHtmlValue: "Season 13 | Episode 4",
      persistedCondensedTextValue: "Season 13 | Episode 4",
      persistedCondensedHtmlValue: "Season 13 | Episode 4",
      isPersistedValueDirty: false,
    },
    titleOverride: {
      attributeId: 41668,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    image: {
      attributeId: 39235,
      entityId: 19518,
      value: "5b6ab4b3-07c0-4027-8cb2-8fbf9177b607",
      valueFormatted:
        "<img src='/GetImage.ashx?guid=5b6ab4b3-07c0-4027-8cb2-8fbf9177b607' class='img-responsive' />",
      persistedTextValue:
        "Clients_SisterhoodPodcast_Web_1920x1080_C_14_PROOF1.png",
      persistedHtmlValue:
        "<img src='/GetImage.ashx?guid=5b6ab4b3-07c0-4027-8cb2-8fbf9177b607' class='img-responsive' />",
      persistedCondensedTextValue:
        "Clients_SisterhoodPodcast_Web_1920x1080_C_14_PROOF1.png",
      persistedCondensedHtmlValue:
        "<img src='/GetImage.ashx?guid=5b6ab4b3-07c0-4027-8cb2-8fbf9177b607&width=120' class='img-responsive' />",
      isPersistedValueDirty: false,
    },
    video: {
      attributeId: 41666,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    videoLink: {
      attributeId: 50340,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    audio: {
      attributeId: 41665,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    metadata: {
      attributeId: 53862,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    shareMessage: {
      attributeId: 55389,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    hideFromSearch: {
      attributeId: 70701,
      entityId: 19518,
      value: "False",
      valueFormatted: "Show in Search",
      persistedTextValue: "Show in Search",
      persistedHtmlValue: "Show in Search",
      persistedCondensedTextValue: "N",
      persistedCondensedHtmlValue: "N",
      isPersistedValueDirty: false,
    },
    scriptures: {
      attributeId: 71610,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    theme: {
      attributeId: 115363,
      entityId: 19518,
      value: "721bcdc0-1eb9-43b4-94f7-5e09b61d1dfa",
      valueFormatted: "Sisterhood",
      persistedTextValue: "Sisterhood",
      persistedHtmlValue: "Sisterhood",
      persistedCondensedTextValue: "Sisterhood",
      persistedCondensedHtmlValue: "Sisterhood",
      isPersistedValueDirty: false,
    },
    contentTags: {
      attributeId: 147849,
      entityId: 19518,
      value: "682f2c6c-6dc8-4aa2-9733-72195cd0481d",
      valueFormatted: "Women",
      persistedTextValue: "Women",
      persistedHtmlValue: "Women",
      persistedCondensedTextValue: "Women",
      persistedCondensedHtmlValue: "Women",
      isPersistedValueDirty: false,
    },
    additionalResources: {
      attributeId: 209106,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    pathname: {
      attributeId: 209133,
      entityId: 19518,
      value: "season-13-episode-4",
      valueFormatted: "season-13-episode-4",
      persistedTextValue: "season-13-episode-4",
      persistedHtmlValue: "season-13-episode-4",
      persistedCondensedTextValue: "season-13-episode-4",
      persistedCondensedHtmlValue: "season-13-episode-4",
      isPersistedValueDirty: false,
    },
    securityDataViews: {
      attributeId: 179741,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    author: {
      attributeId: 113384,
      entityId: 19518,
      value: "c97c6669-c083-4e8e-919d-4396b8064e0b",
      valueFormatted: "Julie Mullins",
      persistedTextValue: "Julie Mullins",
      persistedHtmlValue: "Julie Mullins",
      persistedCondensedTextValue: "Julie Mullins",
      persistedCondensedHtmlValue: "Julie Mullins",
      isPersistedValueDirty: false,
    },
    cardTitle: {
      attributeId: 113385,
      entityId: 19518,
      value: "",
      valueFormatted: "",
      persistedTextValue: "",
      persistedHtmlValue: "",
      persistedCondensedTextValue: "",
      persistedCondensedHtmlValue: "",
      isPersistedValueDirty: false,
    },
    url: {
      attributeId: 113386,
      entityId: 19518,
      value: "season-13-episode-4",
      valueFormatted: "season-13-episode-4",
      persistedTextValue: "season-13-episode-4",
      persistedHtmlValue: "season-13-episode-4",
      persistedCondensedTextValue: "season-13-episode-4",
      persistedCondensedHtmlValue: "season-13-episode-4",
      isPersistedValueDirty: false,
    },
    callsToAction: {
      attributeId: 113389,
      entityId: 19518,
      value:
        "LISTEN ON APPLE PODCASTS ^https://podcasts.apple.com/us/podcast/how-to-be-the-encourager-everyone-needs-including-you/id1589265192?i=1000718241096|LISTEN ON SPOTIFY ^https://open.spotify.com/episode/43BPBQivl2vKWKqwuIfXZb|LISTEN ON AMAZON MUSIC ^https://music.amazon.com/podcasts/421132ba-bcf7-41c3-8104-73785c14b1f9/episodes/42013466-3d59-4c2d-9f37-d7c1bf960a70/so-good-sisterhood-how-to-be-the-encourager-everyone-needs%E2%80%94including-you",
      valueFormatted:
        "LISTEN ON APPLE PODCASTS : https://podcasts.apple.com/us/podcast/how-to-be-the-encourager-everyone-needs-including-you/id1589265192?i=1000718241096, LISTEN ON SPOTIFY : https://open.spotify.com/episode/43BPBQivl2vKWKqwuIfXZb, LISTEN ON AMAZON MUSIC : https://music.amazon.com/podcasts/421132ba-bcf7-41c3-8104-73785c14b1f9/episodes/42013466-3d59-4c2d-9f37-d7c1bf960a70/so-good-sisterhood-how-to-be-the-encourager-everyone-needs—including-you",
      persistedTextValue:
        "LISTEN ON APPLE PODCASTS : https://podcasts.apple.com/us/podcast/how-to-be-the-encourager-everyone-needs-including-you/id1589265192?i=1000718241096, LISTEN ON SPOTIFY : https://open.spotify.com/episode/43BPBQivl2vKWKqwuIfXZb, LISTEN ON AMAZON MUSIC : https://music.amazon.com/podcasts/421132ba-bcf7-41c3-8104-73785c14b1f9/episodes/42013466-3d59-4c2d-9f37-d7c1bf960a70/so-good-sisterhood-how-to-be-the-encourager-everyone-needs—including-you",
      persistedHtmlValue:
        "LISTEN ON APPLE PODCASTS : https://podcasts.apple.com/us/podcast/how-to-be-the-encourager-everyone-needs-including-you/id1589265192?i=1000718241096, LISTEN ON SPOTIFY : https://open.spotify.com/episode/43BPBQivl2vKWKqwuIfXZb, LISTEN ON AMAZON MUSIC : https://music.amazon.com/podcasts/421132ba-bcf7-41c3-8104-73785c14b1f9/episodes/42013466-3d59-4c2d-9f37-d7c1bf960a70/so-good-sisterhood-how-to-be-the-encourager-everyone-needs—including-you",
      persistedCondensedTextValue: "LISTEN ON APPLE PODCASTS :...",
      persistedCondensedHtmlValue: "LISTEN ON APPLE PODCASTS :...",
      isPersistedValueDirty: false,
    },
    rockLabel: {
      attributeId: 153660,
      entityId: 19518,
      value: "Season 13 | Episode 4",
      valueFormatted: "Season 13 | Episode 4",
      persistedTextValue: "Season 13 | Episode 4",
      persistedHtmlValue: "Season 13 | Episode 4",
      persistedCondensedTextValue: "Season 13 | Episode 4",
      persistedCondensedHtmlValue: "Season 13 | Episode 4",
      isPersistedValueDirty: false,
    },
    podcastSeason: {
      attributeId: 201088,
      entityId: 19518,
      value: "83f2d76b-5aa8-49e7-a1cd-cc7cd60ff7dc",
      valueFormatted: "Season 13",
      persistedTextValue: "Season 13",
      persistedHtmlValue: "Season 13",
      persistedCondensedTextValue: "Season 13",
      persistedCondensedHtmlValue: "Season 13",
      isPersistedValueDirty: false,
    },
    media: {
      attributeId: 207848,
      entityId: 19518,
      value: "de076893-b30e-43bd-ab55-6cbb882ae6b7",
      valueFormatted:
        "<img src='https://embed-ssl.wistia.com/deliveries/6c9d0f45515963944a38587e834213a5.jpg' alt='How to Be the Encourager Everyone Needs—Including You - SGS 13.4' class='img-responsive' />",
      persistedTextValue:
        "How to Be the Encourager Everyone Needs—Including You - SGS 13.4",
      persistedHtmlValue:
        "<img src='https://embed-ssl.wistia.com/deliveries/6c9d0f45515963944a38587e834213a5.jpg' alt='How to Be the Encourager Everyone Needs—Including You - SGS 13.4' class='img-responsive' />",
      persistedCondensedTextValue:
        "How to Be the Encourager Everyone Needs—Including You - SGS 13.4",
      persistedCondensedHtmlValue:
        "<img src='https://embed-ssl.wistia.com/deliveries/6c9d0f45515963944a38587e834213a5.jpg' alt='How to Be the Encourager Everyone Needs—Including You - SGS 13.4' class='img-responsive grid-img' />",
      isPersistedValueDirty: false,
    },
  },
  id: 19518,
  idKey: "l6bpz1M0Pz",
  guid: "e9676fe4-1e87-451d-b6b1-7a33a8b13a10",
  foreignId: null,
  foreignGuid: null,
  foreignKey: null,
};
