export const twentyOneDaysDevotionalData: {
  label: string;
  value: string;
  content: string;
}[] = [
  {
    label: "Day 1",
    value: "day1",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 2",
    value: "day2",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 3",
    value: "day3",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 4",
    value: "day4",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 5",
    value: "day5",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 6",
    value: "day6",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 7",
    value: "day7",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 8",
    value: "day8",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 9",
    value: "day9",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 10",
    value: "day10",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 11",
    value: "day11",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 12",
    value: "day12",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 13",
    value: "day13",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 14",
    value: "day14",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 15",
    value: "day15",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 16",
    value: "day16",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 17",
    value: "day17",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 18",
    value: "day18",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 19",
    value: "day19",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 20",
    value: "day20",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
  {
    label: "Day 21",
    value: "day21",
    content:
      "<div style='display: flex; flex-direction: column; gap: 16px; font-size: 19px;'><h3 style='font-weight: bold;'>What Does It Mean to Say Yes to Jesus?</h3><p>You said yes to Jesus—and as your new church family, we’re really proud of you!<br/></br> There are a lot of ways you might hear people talk about saying yes to Jesus. You might hear phrases like “committing your life to Jesus,” “becoming a Christian,” “getting saved,” or “choosing to follow Jesus.”  <br/> But what does it mean to follow Jesus? What changes and what doesn’t? And why does anything have to change? Those are some of the questions this book will help you answer.<br/></br> So, let’s start with that first question. What does it mean to say yes to Jesus? </br><br/> Following Jesus means becoming like Him. But who is Jesus, and why would we want to be more like Him? </br></br> To answer that question, we need to go to the first book of the Bible, Genesis. It tells us that in the beginning, God made the world, humanity included. He gave us the job of enjoying and caring for what He made. But humanity made choices that hurt us, others, and the world. These choices—what the Bible calls sin—separated us from our perfect God and limited our ability to do the job He had given us.</br></br>Centuries later, God’s Son entered the world as a baby named Jesus. Jesus lived around 33 years on Earth and spent that time showing us the best way to live—by loving God and loving others. Then He closed the separation between us and God, His Father, by dying on a cross and rising from the dead.</br></br>Why would Jesus, fully God and fully man, have made this kind of sacrifice for us? Before His death, Jesus sat down with a person named Nicodemus late one night. Nicodemus had lots of questions about what it meant to follow Jesus. As part of His response to Nicodemus’ questions, Jesus shared some of His most famous words:</br></br></p> <blockquote>For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life. God sent his Son into the world not to judge the world, but to save the world through him.  - Matthew 6:34</blockquote> <p>God’s love for us is so great that Jesus was willing to die for our sins so we could be a part of His family forever. That’s the kind of love that would make anyone want to say yes to His love, forgiveness, and new way of life.</br></br>Tomorrow, we’ll talk about how that happens, but today, let’s consider Jesus’ answer as we talk with Him in prayer.</br></br>Pray with your own words, or try these:</br></br>God, I have decided to trust that Jesus is your Son who came to save me and the world. I don’t know everything about what this means yet, but I do want to follow Jesus and live His way. Thank you for loving me enough to send Jesus. Thank you for inviting me into your family. Amen.</br></br></p></div>",
  },
];
